version: '3.4'

services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  sql-server-db:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Odb12345678"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql

  monthlycosts-api:
    image: monthlycostsapi
    build:
      context: .
      dockerfile: src/01 - Presentation/MonthlyCosts.API/Dockerfile
    container_name: monthlycosts-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DbConnection=$MONTHLY_COST_DBCONNECTION"
      - "MessageBusSettings__ConnectionString=$MONTHLY_COST_MESSAGE_BUS_CONNECTION"
    depends_on:
      - mongo-db
      - sql-server-db
    ports:
      - "8002:80"
      - "8003:443"

volumes:
  mongodb_data:
  sqlserver_data:
