name: CD - Monthly costs API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://monthlycosts.azurecr.io/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: monthlycosts.azurecr.io/${{ secrets.DOCKER_USERNAME }}/monthlycostsapi:${{ github.sha }}
        file: ./src/01 - Presentation/MonthlyCosts.API/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'monthly-costs'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_53f0eac2f53e4f4fb20b909b468e7d39 }}
        images: 'monthlycosts.azurecr.io/${{ secrets.DOCKER_USERNAME }}/monthlycostsapi:${{ github.sha }}'
